<?php
namespace ERD\GridSystemBundle\Tests\Model;
use ERD\GridSystemBundle\Model\CSSObject;

/**
 * Test class for CSSObject.
 * Generated by PHPUnit on 2012-07-03 at 04:48:07.
 */
class CSSObjectTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var CSSObject
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CSSObject('testSelector');
    }


    public function testGetSelector()
    {
        $this->assertTrue($this->object->getSelector()=='testSelector');
    }

    public function testGetSetBaseDeclarations()
    {
        $this->assertEquals(array(), $this->object->getBaseDeclarations());
        
        $this->object->setBaseDeclarations(array('test'=>'test'));
        
        $this->assertEquals(array('test'=>'test'), $this->object->getBaseDeclarations());
    }

}
?>
